# Generated by Django 5.1.4 on 2024-12-07 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookormovie',
            name='genre',
        ),
        migrations.AddField(
            model_name='bookormovie',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app1.genre'),
        ),
    ]
