# Generated by Django 5.1.4 on 2024-12-07 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_bookormovie_genre_bookormovie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookormovie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app1.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
